# Generated by Django 3.2.9 on 2021-11-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('excerpt', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
    ]
