# Generated by Django 3.2.9 on 2021-11-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodblog", "0004_auto_20211129_1637"),
    ]

    operations = [
        migrations.AddField(
            model_name="textblock",
            name="name",
            field=models.CharField(default="option", max_length=100),
        ),
    ]
