# Generated by Django 3.2.9 on 2021-12-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0005_textblock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(),
        ),
    ]
