# Generated by Django 3.2.9 on 2021-12-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodblog", "0011_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(default="no-slug"),
        ),
    ]
