# Generated by Django 3.2.9 on 2021-12-20 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0012_alter_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 15, 35, 25, 846104)),
        ),
    ]
