# Generated by Django 3.2.9 on 2021-12-20 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("foodblog", "0012_alter_tag_slug"),
        ("foodblog", "0014_alter_comment_pub_date"),
    ]

    operations = []
